# Generated by Django 3.1.13 on 2022-05-06 02:55

import app.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('front_text', models.CharField(max_length=280)),
                ('back_text', models.CharField(max_length=280)),
                ('front_Img', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('back_Img', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator_username', models.CharField(max_length=50)),
                ('deckName', models.CharField(max_length=50)),
                ('dateCreated', models.DateField()),
                ('isFavourite', models.BooleanField(default=False)),
                ('editable', models.BooleanField(default=False)),
                ('cardCount', models.IntegerField(default=0)),
                ('user_account', models.ForeignKey(default=app.models.getUserOrCreate, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CardLedger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study_date', models.DateField(default=None)),
                ('ELO', models.IntegerField(default=0)),
                ('leech', models.IntegerField(default=0)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.card')),
                ('user_account', models.ForeignKey(default=app.models.getUserOrCreate, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='card',
            name='deck',
            field=models.ForeignKey(default=app.models.getDeckorCreate, on_delete=django.db.models.deletion.DO_NOTHING, to='app.deck'),
        ),
    ]
