# Generated by Django 3.1.13 on 2022-04-24 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('cardId', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('deckId', models.IntegerField()),
                ('userId', models.IntegerField()),
                ('study_date', models.DateField(default=None)),
                ('ELO', models.IntegerField(default=0)),
                ('leech', models.IntegerField(default=0)),
                ('front_text', models.CharField(max_length=280)),
                ('frontImg', models.URLField(null=True)),
                ('back_text', models.CharField(max_length=280)),
                ('backImg', models.URLField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('deckId', models.IntegerField(primary_key=True, serialize=False)),
                ('userId', models.IntegerField()),
                ('creatorId', models.IntegerField()),
                ('deckName', models.CharField(max_length=50)),
                ('dateCreated', models.DateField()),
                ('isFavourite', models.BooleanField(default=False)),
                ('editable', models.BooleanField(default=False)),
                ('cardCount', models.IntegerField(default=0)),
            ],
        ),
    ]
