# Generated by Django 3.1.13 on 2022-04-24 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='userId',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='deck',
            name='userId',
            field=models.IntegerField(default=0),
        ),
    ]
