# Generated by Django 3.1.13 on 2022-04-29 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='deckId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.deck'),
        ),
        migrations.AlterField(
            model_name='card',
            name='userId',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='deck',
            name='userId',
            field=models.IntegerField(default=0),
        ),
    ]
