# Generated by Django 3.1.13 on 2022-05-12 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20220512_1457'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cardledger',
            old_name='deck',
            new_name='deckCL',
        ),
        migrations.RenameField(
            model_name='cardledger',
            old_name='user_account',
            new_name='userCL',
        ),
    ]
