# Generated by Django 3.1.13 on 2022-04-29 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20220424_1344'),
        ('app', '0002_auto_20220429_0858'),
    ]

    operations = [
    ]
