# Generated by Django 3.1.13 on 2022-05-12 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20220512_1502'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cardledger',
            old_name='deckCL',
            new_name='deck',
        ),
        migrations.RenameField(
            model_name='cardledger',
            old_name='userCL',
            new_name='user_account',
        ),
    ]
