# Generated by Django 3.1.13 on 2022-05-06 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20220505_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deck',
            name='dateCreated',
            field=models.DateField(blank=True, null=True),
        ),
    ]
