# Generated by Django 3.1.13 on 2022-04-29 13:11

import app.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0004_merge_20220429_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deck',
            name='userId',
            field=models.ForeignKey(default=app.models.getUserIDorCreate, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
