# Generated by Django 3.1.13 on 2022-05-06 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20220505_2302'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='deck',
            new_name='dec',
        ),
    ]
