# Generated by Django 3.1.13 on 2022-05-03 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20220429_0912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='backImg',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='frontImg',
            field=models.URLField(blank=True, null=True),
        ),
    ]
