# Generated by Django 3.1.13 on 2022-05-05 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20220502_2136'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='deckId',
            new_name='deck',
        ),
        migrations.RenameField(
            model_name='card',
            old_name='userId',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='deck',
            old_name='creatorId',
            new_name='creator',
        ),
        migrations.RenameField(
            model_name='deck',
            old_name='userId',
            new_name='user',
        ),
    ]
